export const wordImages = {
    // Easy words (4 letters)
    cake: 'https://via.placeholder.com/300x200.png?text=Cake',
    fish: 'https://via.placeholder.com/300x200.png?text=Fish',
    bird: 'https://via.placeholder.com/300x200.png?text=Bird',
    play: 'https://via.placeholder.com/300x200.png?text=Play',
    tree: 'https://via.placeholder.com/300x200.png?text=Tree',
    book: 'https://via.placeholder.com/300x200.png?text=Book',
    love: 'https://via.placeholder.com/300x200.png?text=Love',
    star: 'https://via.placeholder.com/300x200.png?text=Star',
    quip: 'https://via.placeholder.com/300x200.png?text=Quip',
    zest: 'https://via.placeholder.com/300x200.png?text=Zest',
    jolt: 'https://via.placeholder.com/300x200.png?text=Jolt',
    yolk: 'https://via.placeholder.com/300x200.png?text=Yolk',
    // Medium words (5 letters)
    house: 'https://via.placeholder.com/300x200.png?text=House',
    smile: 'https://via.placeholder.com/300x200.png?text=Smile',
    world: 'https://via.placeholder.com/300x200.png?text=World',
    green: 'https://via.placeholder.com/300x200.png?text=Green',
    chair: 'https://via.placeholder.com/300x200.png?text=Chair',
    table: 'https://via.placeholder.com/300x200.png?text=Table',
    light: 'https://via.placeholder.com/300x200.png?text=Light',
    dream: 'https://via.placeholder.com/300x200.png?text=Dream',
    quilt: 'https://via.placeholder.com/300x200.png?text=Quilt',
    zebra: 'https://via.placeholder.com/300x200.png?text=Zebra',
    jumbo: 'https://via.placeholder.com/300x200.png?text=Jumbo',
    vivid: 'https://via.placeholder.com/300x200.png?text=Vivid',
    // Hard words (6 letters)
    school: 'https://via.placeholder.com/300x200.png?text=School',
    flower: 'https://via.placeholder.com/300x200.png?text=Flower',
    bright: 'https://via.placeholder.com/300x200.png?text=Bright',
    planet: 'https://via.placeholder.com/300x200.png?text=Planet',
    circle: 'https://via.placeholder.com/300x200.png?text=Circle',
    friend: 'https://via.placeholder.com/300x200.png?text=Friend',
    market: 'https://via.placeholder.com/300x200.png?text=Market',
    winter: 'https://via.placeholder.com/300x200.png?text=Winter',
    quartz: 'https://via.placeholder.com/300x200.png?text=Quartz',
    zodiac: 'https://via.placeholder.com/300x200.png?text=Zodiac',
    jigsaw: 'https://via.placeholder.com/300x200.png?text=Jigsaw',
    vortex: 'https://via.placeholder.com/300x200.png?text=Vortex',
  };